# Application
spring.application.name=inventory-backend
server.port=8080

# PostgreSQL Database
spring.datasource.url=jdbc:postgresql://localhost:5434/inventory
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# GraphQL
spring.graphql.graphiql.enabled=true
spring.graphql.path=/graphql

# Security
spring.security.user.name=admin
spring.security.user.password=admin123

spring.graphql.schema.inspection.enabled=false
logging.level.org.springframework.graphql=DEBUG
spring.jpa.open-in-view=true


supabase.url=https://gctcznmoeorwnmqhevop.supabase.co
supabase.anon-key=yJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdjdGN6bm1vZW9yd25tcWhldm9wIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODQ3Mjg0ODcsImV4cCI6MjEwMDMwNDQ4N30.7TQt5lbfEjMT6Lmc57HIDqNv_qFeudpTkUMo-gB1A1s